using System.IO;
using System.Text;

namespace UIX.Editor.Pipeline
{
    /// <summary>
    /// Generates C# binding code for screens.
    /// </summary>
    public static class UIXBindingCodeGen
    {
        public static void Generate(string screenName, string viewModelType, string outputPath)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// AUTO-GENERATED FILE. DO NOT EDIT.");
            sb.AppendLine();
            sb.AppendLine($"public partial class {screenName}_Bindings : UIX.Binding.UIXBindingBase");
            sb.AppendLine("{");
            sb.AppendLine("    public override void Bind(UIX.Binding.ViewModel viewModel, UnityEngine.GameObject root)");
            sb.AppendLine("    {");
            sb.AppendLine($"        var vm = ({viewModelType})viewModel;");
            sb.AppendLine("        // Bindings generated by UIX");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public override void Unbind() { }");
            sb.AppendLine("}");

            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            File.WriteAllText(outputPath, sb.ToString());
        }
    }
}
